# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
parameters:
    repo:
        type: string
        default: "rsksmart/rskj.git"
    version:
        type: string
        default: ""
    branch:
        type: string
        default: "master"
    slack_channel:
        type: string
        default: "integration-tests"
orbs:
  slack: circleci/slack@4.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:17.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/tmp

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
          name: Clone and Build RSKj
          command: |
                    GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_fingerprint'
                    git clone -b << pipeline.parameters.branch >> git@github.com:<< pipeline.parameters.repo >>  ~/rsksmart/rskj
                    cd ~/rsksmart/rskj/
                    ./configure.sh
                    ./gradlew clean build -x test
                    cd ~/rsksmart/rskj/rskj-core/build/libs/
                    f=`ls *-all.jar`
                    version=`echo $f | cut -c 11-15`
                    echo "export VERSION_FOR_SLACK='${version}'" >> $BASH_ENV

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run:
          name: Start RSKj & Run JMeter
          command: |
                    java -Dminer.client.autoMine=true -Dtransaction.accountTxRateLimit.enabled=false -Drpc.providers.web.ws.enabled=true -Drpc.modules.debug.enabled=true -Drpc.modules.trace.enabled=true -cp ~/rsksmart/rskj/rskj-core/build/libs/rskj-core-*-all.jar co.rsk.Start --regtest  nohup &               
                    until nc -z 127.0.0.1 4444
                    do
                      echo "Waiting for RskJ..."
                      sleep 1
                    done
                    mvn verify

      - store_artifacts:
          path: ~/tmp/target/jmeter/results
          destination: ~/tmp/results
          
      - slack/notify:
          channel: << pipeline.parameters.slack_channel >>
          custom: |
            {
                "blocks": [
                    {
                        "type": "header",
                        "text": {
                            "type": "plain_text",
                            "text": "RskJ JMeter Tests Passed :white_check_mark:",
                            "emoji": true
                        }
                    },
                    {
                        "type": "section",
                        "fields": [
                            {
                                "type": "mrkdwn",
                                "text": "*RSKj Repository*: << pipeline.parameters.repo >>"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*RSKj Branch*: << pipeline.parameters.branch >>"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*RSKj Version*: ${VERSION_FOR_SLACK}"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*Tests Branch*: ${CIRCLE_BRANCH}"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*Requester*: ${CIRCLE_USERNAME}"
                            }
                        ]
                    },
                    {
                        "type": "actions",
                        "elements": [
                            {
                                "type": "button",
                                "text": {
                                    "type": "plain_text",
                                    "text": "View Job"
                                },
                                "url": "${CIRCLE_BUILD_URL}"
                            }
                        ]
                    }
                ]
                }
          event: pass

      - slack/notify:
          channel: << pipeline.parameters.slack_channel >>
          custom: |
            {
                "blocks": [
                    {
                        "type": "header",
                        "text": {
                            "type": "plain_text",
                            "text": "RskJ JMeter Tests Failed :red_circle:",
                            "emoji": true
                        }
                    },
                    {
                        "type": "section",
                        "fields": [
                            {
                                "type": "mrkdwn",
                                "text": "*RSKj Repository*: << pipeline.parameters.repo >>"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*RSKj Branch*: << pipeline.parameters.branch >>"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*RSKj Version*: ${VERSION_FOR_SLACK}"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*Tests Branch*: ${CIRCLE_BRANCH}"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*Requester*: ${CIRCLE_USERNAME}"
                            }
                        ]
                    },
                    {
                        "type": "actions",
                        "elements": [
                            {
                                "type": "button",
                                "text": {
                                    "type": "plain_text",
                                    "text": "View Job"
                                },
                                "url": "${CIRCLE_BUILD_URL}"
                            }
                        ]
                    }
                ]
                }
          event: fail

workflows:
    commit:
        jobs:
            - build
    daily:
        triggers:
            - schedule:
                cron: "22 01 * * *"
                filters:
                    branches:
                        only:
                            - master
        jobs:
            - build
